#!/bin/bash
# Abstract : Chroot into a selected system if present.
# Author   : github.com/kreyren
# License  : GPLv2

CALLME="KCHROOT"

# CHECK ROOT
checkroot () {
	if [[ $UID == 0 ]]; then
		echo "something" 2&> /dev/null
		#No need to bother with "wow you are roooot!!"

		elif [[ -x "$(command -v sudo)" ]]; then
			echo -e "\e[1;32m$CALLME:\e[0m Failed to aquire root permission, trying using sudo."
			sudo $0 "$@"
			exit 1

		#TODO: Add sudo alternatives

		elif [[ ! -x "$(command -v sudo)" ]]; then
			echo -e "\e[1;32m$CALLME:\e[0m Failed to aquire root permission, trying using su."
			su -c "$0 $@"
			exit 1

	fi
}

chrootme () {
	mount --rbind /dev ${MOUNT}/dev || echo 30
	mount --make-rslave ${MOUNT}/dev || echo 31
	mount -t proc /proc ${MOUNT}/proc || echo 32
	mount --rbind /sys ${MOUNT}/sys || echo 33
	mount --make-rslave ${MOUNT}/sys || echo 34
	mount --rbind /tmp ${MOUNT}/tmp || echo 35
	chroot ${MOUNT} /bin/bash
}

chroot-gentoo () {
	if [[ -e /mnt/gentoo ]]; then
		MOUNT="/mnt/gentoo"
		chrootme

		else
			echo "FATAL: /mnt/gentoo not mounted"
			exit 0
	fi
}



case $1 in
	--gentoo )
	checkroot $@
	chroot-gentoo
	;;

	*)
	echo "STUB - Select argument"
	exit 0
	;;
esac